AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Arbitrum Transaction Enforcer template

Parameters:
  StackName:
    Description: The cloudformation stack name, MUST be lower case
    Type: String
  DomainName: 
    Description: The domain name of the existing Route 53 hosted zone, should match HostedZoneId
    Type: String
  HostedZoneId:
    Description: The ID of the existing Route 53 hosted zone, should match DomainName
    Type: String

Resources:
  UI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: packages/ui/template.yml
      Parameters:
        StackName: !Ref StackName
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId

Outputs:
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID from the UI stack"
    Value: !GetAtt UI.Outputs.CloudFrontDistributionId
  CloudFrontUrl:
    Description: "CloudFront Domain Name from the UI stack"
    Value: !GetAtt UI.Outputs.CloudFrontUrl
