/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReviewImport } from './routes/review'
import { Route as IndexImport } from './routes/index'
import { Route as ActivityIndexImport } from './routes/activity.index'
import { Route as ActivityTxImport } from './routes/activity.$tx'

// Create/Update Routes

const ReviewRoute = ReviewImport.update({
  path: '/review',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActivityIndexRoute = ActivityIndexImport.update({
  path: '/activity/',
  getParentRoute: () => rootRoute,
} as any)

const ActivityTxRoute = ActivityTxImport.update({
  path: '/activity/$tx',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewImport
      parentRoute: typeof rootRoute
    }
    '/activity/$tx': {
      id: '/activity/$tx'
      path: '/activity/$tx'
      fullPath: '/activity/$tx'
      preLoaderRoute: typeof ActivityTxImport
      parentRoute: typeof rootRoute
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ReviewRoute,
  ActivityTxRoute,
  ActivityIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/review",
        "/activity/$tx",
        "/activity/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/review": {
      "filePath": "review.tsx"
    },
    "/activity/$tx": {
      "filePath": "activity.$tx.tsx"
    },
    "/activity/": {
      "filePath": "activity.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
